name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Backend:
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.head.ref, '#cesi') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      trout:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: trout
          MARIADB_DATABASE: trout
          MARIADB_USER: trout
          MARIADB_PASSWORD: trout
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      BDD_HOST: 127.0.0.1
      BDD_PORT: 3306
      BDD_NAME: trout
      BDD_USER: trout
      BDD_PASS: trout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Trout Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -u root -ptrout -e "SHOW_DATABASES"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Check Adrien's Node installation
        run: |
          printf "adrien@github: ~/mono$ node -v\nv16.15.0\n"

      - name: Install dependencies
        run: npm i

      - name: Init Trout
        run: npm run initbdd

      - name: Populate Trout
        run: npm run populate

      - name: Run all tests and coverage
        run: npm run test:cov

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-repport
          path: backend/coverage
          retention-days: 3


